version: '3'

services:
  web:
    image: coinflow/heco-converters-web:latest
    container_name: web
    restart: always
    ports:
      - '80:80'
    privileged: true

networks:
  lend_default:
    driver: bridge
