version: '3'

services:
  web:
    image: ginlink/sheep-web:dev
    container_name: web
    restart: always
    ports:
      - '80:80'
    privileged: true

networks:
  lend_default:
    driver: bridge
